### ISSUE TITLE
Commit/push on workspace close

### ISSUE THREAD

**Issue by jsjoeio** [lostintangent/gitdoc#11]
I understand the intervals (auto-commit every 30 secs), but I wish there were a checkbox to say, "If I close the workspace, and it's dirty, auto-commit and auto-push for me." 

This is in the event that I make changes and close the workspace before it hits the next interval.

**Comment by lostintangent** [comment]
This has now been addressed. By default, changes will be automatically committed when you close VS Code, but this can be disabled by setting the `GitDoc: Commit on Close` setting to `false`. Thanks!
