### ISSUE TITLE
GitDoc not staying enabled

### ISSUE THREAD

**Issue by jsjoeio** [lostintangent/gitdoc#14]
I don't know if this is related to me using VS Code Insiders, but it seems like GitDoc is not staying enabled. I enabled it once, but it doesn't seem to stick. 

I'm going to test saving this setting to my workspace settings which should fix I think.

**Comment by lostintangent** [comment]
This is actually related to #12 😄 Currently, the `GitDoc: Enable` command only enables auto-comitting/pushing for the VS Code session, whereas `GitDoc: Enable (Branch)` actually stores the enablement setting in your workspace. In hindsight, this is highly confusing, and so I'm going to remove the `GitDoc: Enable (Branch)` entirely, and update `GitDoc: Enable` to persist the setting to the workspace. Then, if you only want to enable GitDoc on a specific branch, you can simply checkout that branch, and run the enable command 👍

**Comment by jsjoeio** [comment]
AH! That makes more sense now. Woohoo! Thanks!

**Comment by lostintangent** [comment]
This has now been fixed, and behaves like my previous comment 👍
