### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by jsjoeio** [lostintangent/gitdoc#15]
I'd love to be able to use this on `code-server`. Any chance you'd consider publishing on the [Open VSX Registry](https://open-vsx.org)?

**Comment by lostintangent** [comment]
Unfortunately, I don't have the bandwidth to support other distros of VS Code right now 😦 So I'm going to close this for now, and I can revisit it in the future, once I have a bit more time. Time!
