### ISSUE TITLE
GitDoc gets into loop for pushing

### ISSUE THREAD

**Issue by lucidbard** [lostintangent/gitdoc#16]
VS Code on windows gets into a loop trying to push at start of opening a clean working tree repository. Using latest version of VS Code and Windows.

`Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.30.1.windows.1 from C:\Program Files\Git\cmd\git.exe`

<details>
<summary>
<i>Raw logs </i>
</summary>
`> git push --force origin master
> git push --force origin master
> git push --force origin master
> git push --force origin master
> git push --force origin master
> git push --force origin master
> git push --force origin master
Everything up-to-date
> git status -z -u
> git symbolic-ref --short HEAD
> git push --force origin master
Everything up-to-date
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git push --force origin master
> git config --get commit.template
Everything up-to-date
> git status -z -u
> git push --force origin master
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git push --force origin master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git push --force origin master
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git push --force origin master
Everything up-to-date
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git push --force origin master
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git push --force origin master
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git push --force origin master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
Everything up-to-date
> git push --force origin master
> git status -z -u
> git symbolic-ref --short HEAD
Everything up-to-date
> git push --force origin master
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git push --force origin master
> git config --get commit.template
> git status -z -u
Everything up-to-date
> git push --force origin master
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git push --force origin master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
Everything up-to-date
> git push --force origin master
> git status -z -u
> git symbolic-ref --short HEAD
> git push --force origin master
Everything up-to-date
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git push --force origin master
Everything up-to-date
> git config --get commit.template
Everything up-to-date
> git status -z -u
> git push --force origin master
> git symbolic-ref --short HEAD
Everything up-to-date
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git push --force origin master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
Everything up-to-date
> git push --force origin master
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git push --force origin master
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git push --force origin master
> git config --get commit.template
> git status -z -u
> git push --force origin master
Everything up-to-date
> git symbolic-ref --short HEAD
Everything up-to-date
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Everything up-to-date
> git config --get commit.template
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Everything up-to-date
> git config --get commit.template
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
Everything up-to-date
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
Everything up-to-date
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Everything up-to-date
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
`
</details>

**Comment by lostintangent** [comment]
Hmm interesting 🤔 So just to confirm: you opened up a brand new Git repo, enabled GitDoc, and then it got stuck in this push loop? Did the repo even have any remotes yet?

**Comment by lostintangent** [comment]
Hmm interesting 🤔 So just to confirm: you opened up a brand new Git repo, enabled GitDoc, and then it got stuck in this push loop? Did the repo even have any remotes yet?

**Comment by lucidbard** [comment]
It occured after a single commit on this students computer on a fresh repo with a remote. 

It seems like one of the commands may have not returned the right thing and caused an exception in the github command? I couldn't find any other debug output, and wasn't able to reproduce on my computer, so it could be some other interaction in the environment. They had previously installed github desktop, and a large number of github authorizations appeared before we made sure that vscode was authenticated.

**Comment by lostintangent** [comment]
I haven't been able to repro this issue unfortunately :/ I'll keep taking a look and see if I can figure out what might have gone wrong. Out of curiosity: do you recall what OS the student was using?

**Comment by lucidbard** [comment]
Since I can't reproduce, I'll have to wait until this arises again and reopen it then.

**Comment by lostintangent** [comment]
I haven't been able to repro this either :/ Let me know if you run into it again, and I'd love to help investigate. Thanks!
