### ISSUE TITLE
Gitdoc is polluting every opened project

### ISSUE THREAD

**Issue by zomars** [lostintangent/gitdoc#17]
Whenever I open any project (even if I haven't enabled GitDoc in it) it auto adds `"gitdoc.enabled": false` to `.vscode/settings.json`. This pollutes every repo I open in VS Code.

**Comment by zomars** [comment]
My temporary workaround is to disable the extension per workspace basis.

**Comment by lostintangent** [comment]
Thanks for sending this feedback! That's an unexpected behavior, and so I'll fix it today.

**Comment by lostintangent** [comment]
This has been fixed in the latest extension version. Let me know if you run into any other issues. Thanks!
