### ISSUE TITLE
Rather than display timestamps in UTC (via gitdoc.commitMessageFormat), display in user's time zone instead?

### ISSUE THREAD

**Issue by dmalan** [lostintangent/gitdoc#26]
In educational contexts, where students might not realize that datetimes are being displayed under TIMELINE as UTC, might it be compelling to display those in the user's local time zone instead, as via https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/?

Thanks!

CC @rongxin-liu

**Comment by lostintangent** [comment]
This has been resolved via the time zone setting.
