### ISSUE TITLE
Not available in Visual Studio Code for the Web 😔

### ISSUE THREAD

**Issue by tsathis** [lostintangent/gitdoc#28]
Thanks @lostintangent for providing us this great extension. However, it would be great if I could use this extension on github web editor too. 
Is there any possibility to add that support?

**Comment by ManuelRCastroIglesias** [comment]
And already put, also in Visual Studio Community?

**Comment by lostintangent** [comment]
@ManuelRCastroIglesias that request should probably be a different issue, since it's a completely different set of requirements/work to make happen. I don't have enough experience with VS extension development to take on that task, but I'd be happy to collaborate with someone on it.

**Comment by lostintangent** [comment]
Unfortunately, I don't have the capacity to make this work in VS Code web. GitDoc currently relies entirely on the Git CLI, and so it would be a big change to adapt it to something browser-enabled.

So I'm going to close this for now, but if someone wanted to send a PR, I'd be happy to help review and merge it 👍
