### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Mathitos** [lostintangent/gitdoc#46]
There's a way to make the extension filter by repository name like it already do to file patterns?
I don't want it to auto commit in all of my repos, just a few of them

**Comment by lostintangent** [comment]
By default, GitDoc is disabled for all workspaces. So you shouldn't need to do any repo-based filtering, as long as you only enable GitDoc for the repos you want to auto-commit in.

Are you seeing a different behavior?

**Comment by lostintangent** [comment]
Closing as resolve, per my previous comment. Please re-open this if you have any other questions. Thanks!
