### ISSUE TITLE
Remote extension

### ISSUE THREAD

**Issue by Blazingstar26** [lostintangent/gitdoc#48]
when i open vs code, it always show,"remote extension host terminated unexpectedly 3 times within the last 5 minutes."
Version: 1.72.3
Commit: f69482e92e41b84fb15688f3c0d0a1eca1d5bce3
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 0.1.0

**Comment by lostintangent** [comment]
I'm not sure if this is a GitDoc bug? I can't repro this issue, and there's quite a lot of folks using this extension every day. So if it was consistently crashing the VS Code extension host process, I'd imagine we'd have other reports.

**Comment by lostintangent** [comment]
I'm going to close this for now as "no repro". But please re-open it again if you're seeing this issue, and can narrow it down to GitDoc. Thanks!
