### ISSUE TITLE
Pull on delay doesn't work

### ISSUE THREAD

**Issue by gal064** [lostintangent/gitdoc#49]
Hi,

Pull on delay doesn't work for me. My user settings:
```
    "gitdoc.timeZone": "America/Los_Angeles",
```

My workspace settings:
```
 "gitdoc.commitValidationLevel": "none",
  "gitdoc.enabled": true,
  "gitdoc.autoPull": "afterDelay",
  "gitdoc.autoPullDelay": 30000,
  "git.enableSmartCommit": true,
  "git.postCommitCommand": "sync",
```

Happy to provide more info if helpful.

The reason I need "pull on delay" is that I have a notes repository that I work on mobile + desktop. I keep it open at all times on my laptop so I need it to sync every once in a while.

It appears that it pulls only when it pushes (e.g. on file change)

**Comment by lostintangent** [comment]
I'm unfortunately unable to repro this. I just tried using your exact workspace settings, but changed the pull delay to `1000`, and I see the following in my status bar every second:

![image](https://user-images.githubusercontent.com/116461/199854956-97173496-6a09-454e-9885-451eacea9712.png)

If you tried the same, and then restarted VS Code, do you see this?

**Comment by gal064** [comment]
I got it to work after laptop restart. Thanks
