### ISSUE TITLE
GitDoc: Enable command does not work immediately

### ISSUE THREAD

**Issue by theAkito** [lostintangent/gitdoc#50]
Everytime I enable GitDoc on a repository, it does not work.

Then after some time of playing around and trying out different settings, it may start to work. Or not.

Not sure what the reason for that is.

I know, it's not a settings related issue, though. For example, text files cannot have "errors", so that's not the reason for holding back. All other settings are fine, too.

Still, enabling this extension does not work, as it should.

**Comment by lostintangent** [comment]
Hmm, I'm unfortunately not able to repro this. After you enable GitDoc, do you see this icon in your status bar? I'm just curious which part of the enablement process might be failing for you.

![image](https://user-images.githubusercontent.com/116461/199854317-f63b621c-5199-4ae9-b33b-e25d1a81744b.png)

**Comment by theAkito** [comment]
Meanwhile, the repository that didn't work and caused me to open this issue, started working. Don't know why/how.

I initialised a new repository & enabled GitDoc.

The local `settings.json` has GitDoc enabled `true`.

Yet, the symbol does not appear on the bottom of the editor.

In other projects, the symbol appears, when I open a file, which is part of what may be committed.

Restarting VS Code, etc. did not help.

**Comment by theAkito** [comment]
Okay, I think I get it now. At some point I must've accidentally changed the `filePattern` in Visual Studio Code's global scope, instead of only the Workspace scope, as usual.

Sorry for the erroneous report. It seems to work now. 😃
