### ISSUE TITLE
Feature Request: More Verbose Auto-Commit Messages

### ISSUE THREAD

**Issue by dylan-k** [lostintangent/gitdoc#51]
There's [a different extension out there](https://marketplace.visualstudio.com/items?itemName=MichaelCurrin.auto-commit-msg), which can create more detailed commit messages. Even when squashed, it might help to have these details from something like gitdoc. They more closely resemble the so-called [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). 

I thought to share it here and request this functionality, as it doesn't seem the two work together very well.

**Comment by lostintangent** [comment]
Apologies for the late reply! I was on vacation for a bit. I think this is a great idea, and I actually already do this for my [GistPad extension](https://aka.ms/gistpad). Out of curiosity: are you mostly interested in the commit message that includes the impacted file names and operation? Or did you also want to include the conventional commit prefix?

**Comment by vergenzt** [comment]
I'd love this too! FWIW I've written a script to do this in the past using the output of `git status --porcelain=v1 -z`, and using [`jq`](https://github.com/jqlang/jq) to do the core processing. (I also wrapped this up into a `git commit-on-save` alias to use [`fswatch`](https://github.com/emcrisostomo/fswatch) to trigger the commits. This repo already handles that part, but I'll include it below for context.)

Here's the scripts, in case they're helpful for anybody else:
```ini
# file: ~/.gitconfig
...
[alias]
	summary = "!git status --porcelain=v1 -z | jq -rR git_summarize_changes"
	commit-on-save = "!set -x; fswatch -l20 -0b . | xargs -0n1 git ls-files -z | xargs -0n1 bash -c 'git add -A && git commit -m \"$(git summary)\" && git push'"
```

```jq
# file: ~/.jq
...

def git_summarize_changes: (
  [
    scan("(?x)
      (?: \\A | \\G )
      (?<index_status> (?<is_rename>[RC]) | [^RC] )
      (?<worktree_status> . )
      [ ]
      (?<path> [^\u0000]+ ) 
      (?(<is_rename>) \u0000 (?<renamed_from> [^\u0000]+ ) )
      (?: \\Z | \u0000 )
    ")
    | . as [$index_status, $_, $__, $path, $renamed_path]
    | {$index_status, $path, $renamed_path}
  ]
  | length as $num_files
  | group_by(.index_status)
  | map(

    # https://git-scm.com/docs/git-status#_short_format
    ({
      "M": "update",
      "A": "add",
      "D": "delete",
      "R": "rename",
      "C": "copy",
      "T": "change type of",
    }[.[0].index_status] // empty)

    + " "
    + (
      if $num_files == 1
      then .[] | .path + (if .renamed_path then " from " + .renamed_path else "" end)
      else "\(length) file" + (if length == 1 then "" else "s" end)
      end
    )
  )
  | if length == 0
    then error("No staged git changes")
    else
      join(", ")
      | (.[0:1] | ascii_upcase) + .[1:]
    end
);
```

I think I did some manual testing when I first wrote this (the details of which have been lost to time), but hopefully it's a starting point.

**Comment by lostintangent** [comment]
Does this look close to what you have in mind? https://copilot-workspace.githubnext.com/lostintangent/gitdoc/issues/51?shareId=4f167bda-f665-4e96-9dd8-25850bf01eab

**Comment by lostintangent** [comment]
I just added an integration with Copilot, which uses AI to generate the commit messages: https://github.com/lostintangent/gitdoc?tab=readme-ov-file#ai-generated-commit-messages.

I'll likely need to tune this, but it should provide the most robust solution for creating richer/more robust commit messages. Especially when you set the `GitDoc > AI: Custom Instructions` setting to indicate any stylistic preferences you want it to use.

That said, please let me know if you get a chance to try out this new integration. And if so, where it can be improved 👍🏼
