### ISSUE TITLE
CPU issue GitDoc

### ISSUE THREAD

**Issue by Eleezaveta** [lostintangent/gitdoc#62]
Type: <b>Bug</b>

only activation on startup

Extension version: 0.1.0
VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|19, 46, 74|
|Memory (System)|32.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id 78f3c48c-bc48-4786-99d2-976663d5f723|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lostintangent** [comment]
I haven't been able to repro this :/ So I'm going to close it as no repro and will re-open it if seems to be an issue. There are a ton of GitDoc users, and the lack of reports here indicate it isn't likely a widespread issue.
