### ISSUE TITLE
Not performing auto-anything, no icon in the status bar

### ISSUE THREAD

**Issue by ogulyurdakul** [lostintangent/gitdoc#64]
Hi there, thank you very much for the extension! It will save me from a lot of work if I can get it to work!

Unfortunately, though, I really don't know what to say other than that it doesn't work for me. I tried it with the default settings and non-default setting, trying to get it to auto-do stuff every 5s, commit on close etc. None worked. Then I noticed that the icon in the status bar is not visible, which I think might be telling of something wrong. I only saw it once, but it disappeared very quickly after I clicked on it, and I don't know what to do to see it again.

Update, as I'm writing this: It happened again, while I was tinkering with the settings! It did sync the folder with git, but then the icon disappeared again. I don't know what triggered the extension to work, though.

I know I'm not providing much info, but I really don'T know what to do. I'd be happy to provide more info if asked.

Lastly, I'm using this in a LaTeX directory, and I use the auto features to sync the folder with Overleaf via github. Maybe this is relevant somehow?

**Comment by dylan-k** [comment]
I'm experiencing this issue as well. 
GitDoc v0.1.0 VsCode v1.83.1 on Windows 10

**Comment by triggerx** [comment]
I hope you all figured it out... but for future viewers... make sure you follow the instructions to enable it.  Then you'll see the "mirror" icon at the bottom of VS Code.

**Comment by lostintangent** [comment]
I'm not able to repro this issue, and so I think there may have been a temporary regression in VS Code for a bit. That said, I'm going to close this for now, and please reopen it if you're still encountering a problem 🙏
