### ISSUE TITLE
[Feature Request] Ability to enable gitdoc for a non active vscode project

### ISSUE THREAD

**Issue by rajalokan** [lostintangent/gitdoc#69]
Hi Team. Thanks for this great tool. I use this to sync my `todo, notes and journal` across different devices. I have all my notes, daily todo as part of a github repo called `planner`. Presently, I am able to sync (commit & push) to my github repo when I have `planner` project open in github. 

However, the way I work is with help from [VSNotes](https://marketplace.visualstudio.com/items?itemName=patricklee.vsnotes). This allows me to open my notes & todo from within any of my vscode projects. 

Let's say I'm working on a VSCode python project `foo`, I can still open my notes & todo and update them ( without switching from VSCode project `foot` to `planner`. In my current workflow, `gitdoc` doesn't work as my gitdoc enabled project ( `planner`) isn't active as a VSCode project. 

Is it possible to provide ability to enable gitdoc for a non active vscode project? Pleaset let me know if I'm unclear on my request here. Thanks.

**Comment by lostintangent** [comment]
This behavior is unfortunately out of the scope of GitDoc, and would be more appropriate for a CLI tool.
