### ISSUE TITLE
Manual Operations

### ISSUE THREAD

**Issue by abhibeckert** [lostintangent/gitdoc#77]
Sometimes I find the 30 seconds automatic commit / pull / push timer a little too long, and it's a little annoying when I stop what I'm doing to think about a manual commit message to get my work saved right now, then half way through typing the auto timer triggers and I don't even get to use that message.

It's a small thing but can be quite distracting at times... I'd rather love to be able to type "doc com" into the command pallet to trigger a command named "GitDoc: Manual Commit" (also, Manual Pull/Push should be in there, just because it seems like something people will expect?).

**Comment by lostintangent** [comment]
Hey! This is great feedback. I just addressed this and sent out a Pr: https://copilot-workspace.githubnext.com/lostintangent/gitdoc/issues/77?shareId=53135617-5ba9-42ab-baaa-f956aef4b708

I ended up calling the command "GitDoc: Commit", and I'll try to ship it tomorrow 👍
