### ISSUE TITLE
Feature request: Use Copilot (if available) for autocommit messages

### ISSUE THREAD

**Issue by georgeoshardo** [lostintangent/gitdoc#80]
Hi, this is a great project, I absolutely love it.

VSCode allows one to auto-generate a commit message using Copilot. 

![image](https://github.com/user-attachments/assets/f7cb85de-a16d-42bd-a2f6-af021ddbc2e0)

I'm wondering if it's possible for GitDoc to have Copilot generate the commit message for it? Maybe this issue is related to #51? 

Thank you.

**Comment by lostintangent** [comment]
This has now been shipped!

If you update to the latest GitDoc version, and then enable the `GitDoc > AI: Enabled` setting, then you'll notice that it generates AI-based commit messages for all of your subsequent changes.

Let me know if you have any feedback about the experience! Thanks 🙏🏼

**Comment by georgeoshardo** [comment]
Amazing, thank you!
