### ISSUE TITLE
Missing remote triggers false error message

### ISSUE THREAD

**Issue by RasmusB** [lostintangent/gitdoc#85]
Hello,

I'm running gitdoc on my local notes repo. It only lives locally on my machine for version control, there is no remote repo.

Despite this, I sometimes get a warning message claming that there are remote changes and asking me to perform a force push. Please let me know how I can help track this issue down.

Edit: The exact error message is: "Remote repository contains conflicting changes."

**Comment by lostintangent** [comment]
I figured out the issue and just pushed a fix. I'll deploy an update this afternoon that will include it (0.2.1), so thanks for reporting this 👍🏼
